site_name: Jago and Rajan's COMM documentation project
theme:
  name: material
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Verifying methods: method_verification.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
