site_name: Software Verification With JML
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: intro.md
  - Task 1 - Specifying methods: method_verification.md
  - Task 2 - Specifying class invariants: new_account-registry-task.md
  - Task 3 - Specifying interface implementations: interface-verification.md
  - External resources: external_resources.md
  - Glossary: glossary.md
  - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

