site_name: Documentation for Google Sheets
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Task 1 - Budget Tracker: task1.md
  - Task 2 - "To Do" Tracker: task2.md
  - Task 3 - Merging Sheets: task3.md
  - Glossary : glossary.md
  - Troubleshooting : troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

